##
## @author Adarsh
## @author $LastChangedBy: adarsh $
## @version $Revision: 0001 $, $Date:: 15/6/20 10:12 AM#$
##

spring:
  profiles: default

server:
  servlet:
    context-path: /amt    #context path for the rest services
  port: 8090

# Custom property mqtt configuration
mqtt-properties:
  host: tcp://localhost:1883                                       # mqtt host with port
  clientId: adarsh-model-trains-transformer-                       # client id for mqtt
  username: adarsh                                                 # username for the mqtt
  password: password                                               # user password for the mqtt
  topicSub: /trains/track/#                                        # jmri top level topic name with regex
  lightTopic: /trains/track/light/                                 # jrmi light topic name
  turnoutTopic: /trains/track/turnout/                             # jrmi turnout topic name
  signalTopic: /trains/track/signalhead/                           # jrmi signalhead topic name
  errorTopic: /amt/errors                                          # jrmi error message topic name
  cleanSession: true
  connectionTimeout: 300
  keepAliveInterval: 60
  automaticReconnect: true

# Custom property for nodes configuration
node:
  configurations:
    lightStartingAddress: 10000                   #starting address of the light in whole layout its mandatory value
    signal2LStartingAddress: 20000                #starting address of the 2 light signal in whole layout its mandatory value
    signal3LStartingAddress: 30000                #starting address of the 3 light signal in whole layout its mandatory value
    turnoutServoStartingAddress: 40000            #starting address of the turnout in whole layout its mandatory value
    turnoutSnapStartingAddress: 50000             #starting address of the turnout in whole layout its mandatory value
    signalCacheClearingTime: 8000                 # after every 5 sec job will clean the cache if it is not updated for last 8 sec and if any stale data in cache for specific node
    nodes:
      -
        nodeId: 1                                 # node id/name publish topic will be formed with this id only
        enableNode: true                          # enable the node to process for jmri data
        enablePublishing: true                    # enable the node to publish process data to the mqtt topic
        enableRestApi: false                      # to enable the rest service for the node
        apiEndpointCacheSize: 10                  # cache for rest api to hold the data for service call
        lightStartAddress: 10000
        lightCount: 2                             # 1 pin for each light on the pca9685 board
        signal2LStartAddress: 20000
        signal2LCount: 16                         # 2 pins for each signal light on the pca9685 board  total 16 turnout and every turnout has 2 splitter track (16 * 2 * 2) => 64
        signal3LStartAddress: 30000
        signal3LCount: 5                          # 3 pins for each signal on the pca9685 board  (10 * 3) => 30
        turnoutServoStartAddress: 40000
        turnoutServoCount: 8                      # 1 pin for each servo turnout
        turnoutSnapStartAddress: 50000
        turnoutSnapCount: 8                       # 2 pins for each turnout on the pca9685 board (16 * 2) /16 => 16
        turnoutBoardCount: 2                      # (turnoutCount * 2)/16 :=>  (16 * 2) / 16 => 2
        lightBoardCount: 2                        # (lightCount + signal2LCount + signal3LCount) /16 :=>  (5+32+30)/16 =>  5
        nodeSubscriptionTopic: /amt/node/1/data/  # topic for every node for reading data from spring transformation application

      -
        nodeId: 2
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10100
        lightCount: 5
        signal2LStartAddress: 20100
        signal2LCount: 60
        signal3LStartAddress: 30100
        signal3LCount: 30
        turnoutServoStartAddress: 40100
        turnoutServoCount: 8
        turnoutSnapStartAddress: 50100
        turnoutSnapCount: 8
        turnoutBoardCount: 2
        lightBoardCount: 7
        nodeSubscriptionTopic: /amt/node/2/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 3
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10200
        lightCount: 7
        signal2LStartAddress: 20200
        signal2LCount: 60
        signal3LStartAddress: 30200
        signal3LCount: 18
        turnoutServoStartAddress: 40200
        turnoutServoCount: 16
        turnoutSnapStartAddress: 50200
        turnoutSnapCount: 10
        turnoutBoardCount: 3
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/3/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 4
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10300
        lightCount: 23
        signal2LStartAddress: 20300
        signal2LCount: 10
        signal3LStartAddress: 30300
        signal3LCount: 24
        turnoutServoStartAddress: 40300
        turnoutServoCount: 20
        turnoutSnapStartAddress: 50300
        turnoutSnapCount: 10
        turnoutBoardCount: 4
        lightBoardCount: 3
        nodeSubscriptionTopic: /amt/node/4/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 5
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10400
        lightCount: 45
        signal2LStartAddress: 20400
        signal2LCount: 10
        signal3LStartAddress: 30400
        signal3LCount: 80
        turnoutServoStartAddress: 40400
        turnoutServoCount: 20
        turnoutSnapStartAddress: 50400
        turnoutSnapCount: 12
        turnoutBoardCount: 4
        lightBoardCount: 8
        nodeSubscriptionTopic: /amt/node/5/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 6
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10500
        lightCount: 10
        signal2LStartAddress: 20500
        signal2LCount: 10
        signal3LStartAddress: 30500
        signal3LCount: 45
        turnoutServoStartAddress: 40500
        turnoutServoCount: 20
        turnoutSnapStartAddress: 50500
        turnoutSnapCount: 18
        turnoutBoardCount: 5
        lightBoardCount: 4
        nodeSubscriptionTopic: /amt/node/6/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 7
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10600
        lightCount: 12
        signal2LStartAddress: 20600
        signal2LCount: 10
        signal3LStartAddress: 30600
        signal3LCount: 80
        turnoutServoStartAddress: 40600
        turnoutServoCount: 29
        turnoutSnapStartAddress: 50600
        turnoutSnapCount: 16
        turnoutBoardCount: 4
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/7/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 8
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10700
        lightCount: 7
        signal2LStartAddress: 20700
        signal2LCount: 10
        signal3LStartAddress: 30700
        signal3LCount: 87
        turnoutServoStartAddress: 40700
        turnoutServoCount: 32
        turnoutSnapStartAddress: 507009
        turnoutSnapCount: 16
        turnoutBoardCount: 4
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/8/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 9
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10800
        lightCount: 23
        signal2LStartAddress: 20800
        signal2LCount: 10
        signal3LStartAddress: 30800
        signal3LCount: 24
        turnoutServoStartAddress: 40800
        turnoutServoCount: 32
        turnoutSnapStartAddress: 50800
        turnoutSnapCount: 16
        turnoutBoardCount: 4
        lightBoardCount: 3
        nodeSubscriptionTopic: /amt/node/9/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 10
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 10900
        lightCount: 45
        signal2LStartAddress: 20900
        signal2LCount: 10
        signal3LStartAddress: 30900
        signal3LCount: 80
        turnoutServoStartAddress: 40800
        turnoutServoCount: 32
        turnoutSnapStartAddress: 50800
        turnoutSnapCount: 16
        turnoutBoardCount: 4
        lightBoardCount: 8
        nodeSubscriptionTopic: /amt/node/10/data/
        apiEndpointCacheSize: 10