##
## @author Adarsh
## @author $LastChangedBy: adarsh $
## @version $Revision: 0001 $, $Date:: 15/6/20 10:12 AM#$
##

spring:
  profiles: prod

server:
  servlet:
    context-path: /amt    #context path for the rest services
  port: 8090

# Custom property mqtt configuration
mqtt-properties:
  host: tcp://localhost:1883                                       # mqtt host with port
  clientId: adarsh-model-trains-transformer-                       # client id for mqtt
  username: adarsh                                                 # username for the mqtt
  password: password                                               # user password for the mqtt
  topicSub: /trains/track/#                                        # jmri top level topic name with regex
  lightTopic: /trains/track/light/                                 # jrmi light topic name
  turnoutTopic: /trains/track/turnout/                             # jrmi turnout topic name
  signalTopic: /trains/track/signalhead/                           # jrmi signalhead topic name
  errorTopic: /amt/errors                                          # jrmi error message topic name
  cleanSession: true
  connectionTimeout: 300
  keepAliveInterval: 60
  automaticReconnect: true

# Custom property for nodes configuration
node:
  configurations:
    lightStartingAddress: 1000                    #starting address of the light in whole layout its mandatory value
    turnoutStartingAddress: 10000                 #starting address of the turnout in whole layout its mandatory value
    signal2LStartingAddress: 20000                #starting address of the 2 light signal in whole layout its mandatory value
    signal3LStartingAddress: 30000                #starting address of the 3 light signal in whole layout its mandatory value
    signalCacheClearingTime: 8000                 # after every 5 sec job will clean the cache if its not updated for last 8 sec and if any stale data in cache for specific node
    nodes:
      -
        nodeId: 1                                 # node id/name publish topic will be formed with this id only
        enableNode: true                          # enable the node to process for jmri data
        enablePublishing: true                    # enable the node to publish process data to the mqtt topic
        enableRestApi: false                      # to enable the rest service for the node
        apiEndpointCacheSize: 10                  # cache for rest api to hold the data for service call
        lightStartAddress: 1000
        lightCount: 5                             # 1 pin for each light on the pca9685 board
        turnoutStartAddress: 10000
        turnoutCount: 16                          # 2 pins for each turnout on the pca9685 board (16 * 2) /16 => 16
        signal2LStartAddress: 20000
        signal2LCount: 64                         # 2 pins for each signal light on the pca9685 board  total 16 turnout and every turnout has 2 splitter track (16 * 2 * 2) => 64
        signal3LStartAddress: 30000
        signal3LCount: 30                         # 3 pins for each signal on the pca9685 board  (10 * 3) => 30
        turnoutBoardCount: 2                      # (turnoutCount * 2)/16 :=>  (16 * 2) / 16 => 2
        lightBoardCount: 9                        # (lightCount + signal2LCount + signal3LCount) /16 :=>  (5+32+30)/16 =>  5
        nodeSubscriptionTopic: /amt/node/1/data/  # topic for every node for reading data from spring transformation application

      -
        nodeId: 2
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1100
        lightCount: 5
        turnoutStartAddress: 10100
        turnoutCount: 15
        signal2LStartAddress: 20100
        signal2LCount: 60
        signal3LStartAddress: 30100
        signal3LCount: 30
        turnoutBoardCount: 2
        lightBoardCount: 7
        nodeSubscriptionTopic: /amt/node/2/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 3
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1200
        lightCount: 7
        turnoutStartAddress: 10200
        turnoutCount: 15
        signal2LStartAddress: 20200
        signal2LCount: 60
        signal3LStartAddress: 30200
        signal3LCount: 18
        turnoutBoardCount: 2
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/3/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 4
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1300
        lightCount: 23
        turnoutStartAddress: 10300
        turnoutCount: 10
        signal2LStartAddress: 20300
        signal2LCount: 10
        signal3LStartAddress: 30300
        signal3LCount: 24
        turnoutBoardCount: 2
        lightBoardCount: 3
        nodeSubscriptionTopic: /amt/node/4/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 5
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1400
        lightCount: 45
        turnoutStartAddress: 10400
        turnoutCount: 10
        signal2LStartAddress: 20400
        signal2LCount: 10
        signal3LStartAddress: 30400
        signal3LCount: 80
        turnoutBoardCount: 10
        lightBoardCount: 8
        nodeSubscriptionTopic: /amt/node/5/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 6
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1500
        lightCount: 10
        turnoutStartAddress: 10500
        turnoutCount: 15
        signal2LStartAddress: 20500
        signal2LCount: 10
        signal3LStartAddress: 30500
        signal3LCount: 45
        turnoutBoardCount: 2
        lightBoardCount: 4
        nodeSubscriptionTopic: /amt/node/6/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 7
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1600
        lightCount: 12
        turnoutStartAddress: 10600
        turnoutCount: 48
        signal2LStartAddress: 20600
        signal2LCount: 10
        signal3LStartAddress: 30600
        signal3LCount: 80
        turnoutBoardCount: 6
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/7/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 8
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1700
        lightCount: 7
        turnoutStartAddress: 10700
        turnoutCount: 21
        signal2LStartAddress: 20700
        signal2LCount: 10
        signal3LStartAddress: 30700
        signal3LCount: 87
        turnoutBoardCount: 3
        lightBoardCount: 6
        nodeSubscriptionTopic: /amt/node/8/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 9
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1800
        lightCount: 23
        turnoutStartAddress: 10800
        turnoutCount: 10
        signal2LStartAddress: 20800
        signal2LCount: 10
        signal3LStartAddress: 30800
        signal3LCount: 24
        turnoutBoardCount: 3
        lightBoardCount: 3
        nodeSubscriptionTopic: /amt/node/9/data/
        apiEndpointCacheSize: 10
      -
        nodeId: 10
        enableNode: true
        enablePublishing: true
        enableRestApi: false
        lightStartAddress: 1900
        lightCount: 45
        turnoutStartAddress: 10900
        turnoutCount: 23
        signal2LStartAddress: 20900
        signal2LCount: 10
        signal3LStartAddress: 30900
        signal3LCount: 80
        turnoutBoardCount: 3
        lightBoardCount: 8
        nodeSubscriptionTopic: /amt/node/10/data/
        apiEndpointCacheSize: 10